server:
  port: 8761

spring:
  application:
    name: mall-registry
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/

security:
  basic:
    enabled: true
  user:
    name: lp
    password: 123456
