server:
  port: 8084
  context-path: /order/

spring:
  application:
    name: mall-order
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.225.134:3306/ameshimaMall?useUnicode=true&characterEncoding=utf-8
    username: admin
    password: zn891018"
  redis:
    host: 192.168.225.134
    port: 6379
    password: ;463*
  rabbitmq:
    username: admin
    password: zn891018"
    virtual-host: /mall
    listener:
      simple:
        concurrency: 10
        max-concurrency: 10
        prefetch: 1
        default-requeue-rejected: true
    template:
      retry:
        enabled: true
    host: 192.168.225.134
  jackson:
    default-property-inclusion: non_null

eureka:
  client:
    service-url:
      defaultZone: http://lp:123456@192.168.225.132:8761/eureka/

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mappers/*.xml

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

paypay:
  apiKey: a_Dt9iunotKP_HU2n
  secret: CYWIVDpAPD7iVIYYy68sn2EgmVlvsdnkZSDl08d3nXo=
  assumeMerchant: 630945097324937216
  storeName: 雨島モール
  productionMode: false
  codeType: ORDER_QR