server:
  port: 8080

spring:
  application:
    name: tmall-gateway
  http:
    multipart:
      max-file-size: 5MB

eureka:
  client:
    service-url:
      defaultZone: http://lp:123456@localhost:8761/eureka/
zuul:
  routes:
    basicApi:
      path: /basic/**
      serviceId: tmall-basicData
      stripPrefix: false
    userApi:
      path: /user/**
      serviceId: tmall-user
      stripPrefix: false
    goodsApi:
          path: /goods/**
          serviceId: tmall-goods
          stripPrefix: false
    storeApi:
          path: /store/**
          serviceId: tmall-store
          stripPrefix: false
    orderApi:
          path: /order/**
          serviceId: tmall-order
          stripPrefix: false

# 添加ribbon的超时时间设置
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000