server:
  port: 8081
  context-path: /user/

spring:
  application:
    name: tmall-user
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/tmall?useUnicode=true&characterEncoding=utf-8
    #    url: jdbc:mysql://127.0.0.1:3306/tmallUser?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 3086941018Zn
  redis:
    host: 127.0.0.1
    port: 6379
    password: ;463*
  jackson:
    default-property-inclusion: non_null
  http:
    multipart:
      max-file-size: 5MB

eureka:
  client:
    service-url:
      defaultZone: http://lp:123456@localhost:8761/eureka/

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mappers/*.xml

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

