server:
  port: 8084
  context-path: /order/

spring:
  application:
    name: tmall-order
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/tmallOrder?useUnicode=true&characterEncoding=utf-8&useSSL=false
    url: jdbc:mysql://127.0.0.1:3306/tmall?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 3086941018Zn
  redis:
    host: 127.0.0.1
    port: 6379
    password: ;463*
  rabbitmq:
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        concurrency: 10
        max-concurrency: 10
        prefetch: 1
        default-requeue-rejected: true
    template:
      retry:
        enabled: true
  jackson:
    default-property-inclusion: non_null

eureka:
  client:
    service-url:
      defaultZone: http://lp:123456@localhost:8761/eureka/

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mappers/*.xml

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql