server:
  port: 8086
  context-path: /user/

spring:
  application:
    name: mall-user
  profiles:
    active: mail
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.225.134:3306/ameshimaMall?useUnicode=true&characterEncoding=utf-8
    username: admin
    password: zn891018"
  redis:
    host: 192.168.225.134
    port: 6379
    password: ;463*
  jackson:
    default-property-inclusion: non_null
  http:
    multipart:
      max-file-size: 5MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: group.ameshima@gmail.com
    password: cdjmhllxkcjrvrmz
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    service-url:
      defaultZone: http://lp:123456@192.168.225.132:8761/eureka/

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mappers/*.xml

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql