mail:
  captcha:
    subject: "【雨島モール】認証番号通知"
    text: "雨島モールでの認証番号を通知します。\n
    認証番号:　{captcha}\n\n
    認証番号の有効期限は{time}までです。有効期限をすぎた場合は、認証番号を再発行してください。\n\n
    このメールに心当たりのない場合は、このまま削除してください。\n
    このメールは自動的に送信されています。返信はできません。\n\n
    .・●・✿.｡.:*.・●・✿.｡.:*.・●・✿.｡.:*\n
    雨島グループホールディングス\n
    URL：https://www.ameshimamall.com\n
    〒106-6135　東京都港区六本木6−6−6　六本木ラピュタ\n
    .・●・✿.｡.:*.・●・✿.｡.:*.・●・✿.｡.:*"