server:
  port: 8082
  context-path: /goods/

spring:
  application:
    name: mall-goods
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.225.134:3306/ameshimaMall?useUnicode=true&characterEncoding=utf-8
    username: admin
    password: zn891018"
  redis:
    host: 192.168.225.134
    port: 6379
    password: ;463*
  jackson:
    default-property-inclusion: non_null
  data:
    elasticsearch:
#      cluster-name: tmall-web-service
      cluster-nodes: 192.168.225.134:9300
      properties:
        transport:
          tcp:
            connection_timeout: 120s

eureka:
  client:
    service-url:
      defaultZone: http://lp:123456@192.168.225.132:8761/eureka/

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mappers/*.xml

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql